---
- name: Create configuration backup
  hosts: cisco
  gather_facts: true

  tasks:
    - name: Network backup
      ansible.builtin.include_role:
        name: network.backup.run
      vars:
        operation: backup
        type: full
        data_store:
          local: "./network_backup/"

    - name: Copy network backup to target node
      ansible.builtin.copy:
        src: ./network_backup/
        dest: /tmp/network_backup/
        mode: '0777'
      delegate_to: "{{ target_node }}"