---
- name: Create local backup of network configurations
  hosts: cisco
  gather_facts: true

  tasks:
    - name: Create backup
      ansible.builtin.include_role:
        name: network.backup.run
      vars:
        operation: backup
        type: full
        data_store:
          local: "./network_backup/"

- name: Copy backup from localhost to backup host
  hosts: backup-host

  tasks:
    - name: Copy backup
      ansible.builtin.copy:
        src: ./network_backup/
        dest: /tmp/network/network_backup/
        mode: '0777'
