---
- name: Create brownfield inventory
  hosts: cisco
  gather_facts: false

  tasks:
  - name: Collect network data from Cisco routers
    ansible.builtin.include_role:
      name: network.base.resource_manager
    vars:
      operation: persist
      ansible_network_os: cisco.ios.ios
      resources:
        - 'static_routes'
        - 'interfaces'
        - 'l2_interfaces'
        - 'l3_interfaces'
        - 'ospfv2'
        - 'ospf_interfaces'
      data_store:
        local: "."
    when: inventory_hostname in groups['routers']

  - name: Collect network data from Cisco switches
    ansible.builtin.include_role:
      name: network.base.resource_manager
    vars:
      operation: persist
      ansible_network_os: cisco.ios.ios
      resources:
        - 'vlans'
        - 'static_routes'
        - 'interfaces'
        - 'l2_interfaces'
        - 'l3_interfaces'
      data_store:
        local: "."
    when: inventory_hostname in groups['switches']

- name: Copy network data from localhost to backup host
  hosts: backup-host

  tasks:
    - name: Copy network data
      ansible.builtin.copy:
        src: ./host_vars/
        dest: /tmp/network/host_vars/
        mode: '0777'
