---
- name: Copy network data from backup host to EE
  hosts: backup-host

  tasks:
    - name: Copy network data
      ansible.posix.synchronize:
        src: "/tmp/network/host_vars/"
        dest: "/tmp/host_vars/"
        mode: pull
        recursive: yes

- name: Remediate configuration drift
  hosts: cisco
  gather_facts: true

  tasks:
  - name: Remediate configuration drift on Cisco routers
    ansible.builtin.include_role:
      name: network.base.resource_manager
    vars:
      operation: remediate
      ansible_network_os: cisco.ios.ios
      resources:
        - 'static_routes'
        - 'interfaces'
        - 'l2_interfaces'
        - 'l3_interfaces'
        - 'ospfv2'
        - 'ospf_interfaces'
      data_store:
        local: "/tmp"
    when: inventory_hostname in groups['routers']

  - name: Remediate configuration drift on Cisco switches
    ansible.builtin.include_role:
      name: network.base.resource_manager
    vars:
      operation: remediate
      ansible_network_os: cisco.ios.ios
      resources:
        - 'vlans'
        - 'static_routes'
        - 'interfaces'
        - 'l2_interfaces'
        - 'l3_interfaces'
      data_store:
        local: "/tmp"
    when: inventory_hostname in groups['switches']